apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
spec:
  replicas: {{ .Values.hello.replicas }}
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      containers:
      - name: helloservice
        image: {{ .Values.hello.image }}
        ports:
        - containerPort: 3000
